# Generated by Django 6.0 on 2025-12-07 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=20)),
                ('account_name', models.CharField(help_text='اسم الحساب كما يظهر في المنصة.', max_length=150)),
                ('account_id', models.CharField(blank=True, help_text='المعرّف الداخلي للحساب في منصة السوشيال ميديا (إن وُجد).', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='هل ما زال الحساب متصلاً وصالحًا للاستخدام؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
