# Generated by Django 6.0 on 2025-12-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='account_url',
            field=models.URLField(blank=True, help_text='رابط صفحة الحساب في منصة السوشيال ميديا (اختياري).', max_length=500, null=True),
        ),
    ]
