# Generated by Django 6.0 on 2025-12-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahwar_social', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialAccount',
        ),
    ]
